base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: maistra-builder
    namespace: ci
    tag: "2.6"
  use_build_cache: true
releases:
  arm64-latest:
    release:
      architecture: arm64
      channel: stable
      version: "4.14"
  latest:
    release:
      channel: stable
      version: "4.14"
resources:
  '*':
    limits:
      memory: 16Gi
    requests:
      cpu: "4"
      memory: 4Gi
tests:
- as: maistra-istio-unit-2-6
  commands: |
    make -e T=-v build racetest binaries-test \
    ARTIFACTS="${ARTIFACT_DIR:-}" \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    XDG_CACHE_HOME="/tmp/cache"
  container:
    from: src
  timeout: 1h0m0s
- as: maistra-istio-lint-2-6
  commands: |
    make lint \
    ARTIFACTS="${ARTIFACT_DIR:-}" \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    XDG_CACHE_HOME="/tmp/cache"
  container:
    from: src
  timeout: 1h0m0s
- as: maistra-istio-gencheck-2-6
  commands: |
    make gen-check \
    ARTIFACTS="${ARTIFACT_DIR:-}" \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    XDG_CACHE_HOME="/tmp/cache"
  container:
    from: src
  timeout: 1h0m0s
- as: integ-helm-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-helm-2-6
      cli: latest
      commands: |
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          bash -c \
          "entrypoint \
          prow/integ-suite-kind.sh \
          test.integration.helm.kube.presubmit"
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-security-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-security-2-6
      cli: latest
      commands: |
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          entrypoint \
          prow/integ-suite-kind.sh \
          test.integration.security.kube.presubmit
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-pilot-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-pilot-2-6
      cli: latest
      commands: |
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          entrypoint \
          prow/integ-suite-kind.sh \
          test.integration.pilot.kube.presubmit
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-basic-2-6-arm64
  steps:
    cluster_profile: ossm-aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
      RELEASE_IMAGE_LATEST: release:arm64-latest
    env:
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
      OCP_ARCH: arm64
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-basic-2-6-arm64
      cli: latest
      commands: "# prow/integ-suite-kind.sh test.integration.kube.environment will
        run pilot and security test with flag = TestReachability|TestTraffic. \n#
        This is the same way as upstream does\noc rsh -n \"${MAISTRA_NAMESPACE}\"
        \"${MAISTRA_SC_POD}\" \\\n  entrypoint \\\n  prow/integ-suite-kind.sh \\\n
        \ test.integration.kube.environment\noc cp \"${MAISTRA_NAMESPACE}\"/\"${MAISTRA_SC_POD}\":\"${ARTIFACT_DIR}\"/.
        \"${ARTIFACT_DIR}\"\n"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-servicemesh-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-servicemesh-2-6
      cli: latest
      commands: |
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          entrypoint \
          prow/integ-suite-kind.sh \
          test.integration.servicemesh.kube.presubmit
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-telemetry-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-telemetry-2-6
      cli: latest
      commands: |
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          entrypoint \
          prow/integ-suite-kind.sh \
          test.integration.telemetry.kube.presubmit
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: integ-servicemesh-multicluster-2-6
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
    test:
    - as: copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: integ-servicemesh-multicluster-2-6
      cli: latest
      commands: |
        # temporary workaround: unset ARTIFACTS env for integ-servicemesh-multicluster
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          bash -c \
          "unset ARTIFACTS; \
          entrypoint \
          prow/integ-suite-kind.sh \
          --topology \
          MULTICLUSTER \
          test.integration.servicemesh.kube"
        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
- as: push-images
  steps:
    cluster_profile: ossm-aws
    dependencies:
      RELEASE_IMAGE_LATEST: release:latest
    env:
      BUILD_WITH_CONTAINER: "0"
      GOBIN: /gobin
      GOCACHE: /tmp/cache
      GOMODCACHE: /tmp/cache
      MAISTRA_BUILDER_IMAGE: registry.ci.openshift.org/ci/maistra-builder:2.6
      MAISTRA_NAMESPACE: maistra-e2e-test
      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
      XDG_CACHE_HOME: /tmp/cache
    test:
    - as: maistra-istio-copy-src
      cli: latest
      commands: |
        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
      env:
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 20m0s
    - as: push-images
      cli: latest
      commands: |
        export QUAY_PASS=$(cat /maistra-secrets/password)
        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
          entrypoint \
          sh -c \
          "docker login -u='maistra-dev+prow' \
          -p=${QUAY_PASS} quay.io; \
          make maistra-image.push \
          HUB=quay.io/maistra-dev TAG=PR-${PULL_NUMBER}"
      credentials:
      - mount_path: /maistra-secrets
        name: maistra-dev-prow
        namespace: test-credentials
      env:
      - name: BUILD_WITH_CONTAINER
      - name: MAISTRA_NAMESPACE
      - name: MAISTRA_SC_POD
      - name: XDG_CACHE_HOME
      - name: GOCACHE
      - name: GOBIN
      - name: GOMODCACHE
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      timeout: 2h0m0s
    workflow: servicemesh-istio-e2e-profile
zz_generated_metadata:
  branch: maistra-2.6
  org: maistra
  repo: istio
